### ISSUE TITLE
Installing z3 and z3 ocaml api

### ISSUE THREAD

**Issue by plkumjorn** [ProgramRepair/SearchRepair#2]
I try to rerun the experiments by following the instruction in README. However, I don't understand step 3 clearly.

> Install python, mysql, z3, z3 ocaml api, jdk, gcc in local computer.

Actually, I have no experience about z3. Could you please clarify installing z3 and z3 ocaml api? Now, I downloaded z3 and built it in my local machine, but I don't know how to link it with the project in eclipse and I also have no idea for z3 ocaml api.

However, if I try running the program by and skip installing z3 and z3 ocaml api, at the beginning, the console prints a list of name of directories and four tables are created in mysql with zero row in each table, after that, there are a lot of IOExceptions such as ...

./bughunt/median/97
./bughunt/median/98
java.io.IOException: Cannot run program "./executors/transform": CreateProcess error=193, %1 is not a valid Win32 application
    at java.lang.ProcessBuilder.start(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at Library.Utility.runCProgram(Utility.java:230)
    at ProcessIntroClass.Transform.tranform(Transform.java:22)
    at Experiment.ESearchCase.transformAndInitRunDir(ESearchCase.java:163)
    at Experiment.GroupTest.medianTest(GroupTest.java:78)
    at Experiment.GroupTest.rerun(GroupTest.java:20)
    at test.Main.rerun(Main.java:47)
    at test.Main.main(Main.java:32)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(Unknown Source)
    at java.lang.ProcessImpl.start(Unknown Source)
    ... 11 more
./bughunt/median/98
./bughunt/median/99
java.io.IOException: Cannot run program "./executors/transform": CreateProcess error=193, %1 is not a valid Win32 application
    at java.lang.ProcessBuilder.start(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at Library.Utility.runCProgram(Utility.java:230)
    at ProcessIntroClass.Transform.tranform(Transform.java:22)
    at Experiment.ESearchCase.transformAndInitRunDir(ESearchCase.java:163)
    at Experiment.GroupTest.medianTest(GroupTest.java:78)
    at Experiment.GroupTest.rerun(GroupTest.java:20)
    at test.Main.rerun(Main.java:47)
    at test.Main.main(Main.java:32)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(Unknown Source)
    at java.lang.ProcessImpl.start(Unknown Source)
    ... 11 more
./bughunt/median/99

(Now I'm using Windows10 64-bit)

Thank you so much.

**Comment by brunyuriy** [comment]
Piyawat,

Thank you for the interest in our work.  

SearchRepair depends on z3 and the z3 ocaml library.  To build a
database of snippets, you need the z3 ocaml library.  But to rerun the
experiments using the already built database, you only need z3.

You can find instructions for installing z3 here:
https://github.com/Z3Prover/z3/blob/master/README.md
and z3 ocaml library here:
https://github.com/termite-analyser/z3overlay/blob/master/README.md

In SearchRepair, src/util/Utilities.java invokes z3 from the command
line (see the invokeZ3onFile method).  You just have to make sure,
once you install z3, that the correct executable executes.

The error messages you include suggest that the executables in the 
executors/ directory are not compiled for your machine.  

Good luck!
